grails-app/domain/com/jcatalog/grailsflow/model/process/BasicProcess.groovy
/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.jcatalog.grailsflow.model.process
/**
 * Process class is the base class for all process definitions.
 * All processes supported by the Process Manager can be stored
 * in BasicProcess table according to process definition type.
 *
 * Each process should have definition for processTypeID.
 * The static fields for transitions and nodes should be described too.
 *
 * TODO: Add mechanism of constraints for Process subclasses like Grails has
 * for Domain classes.
 *
 * TODO: Process should contain the list of attachments and possibly
 * the constraints to nodes and variables.
 *
 * TODO: Perhaps BasicProcess should be renamed to Flow
 * (in this case all subclasses should ends with 'Flow' word)
 *
 * @author Stephan Albers
 * @author July Karpey
 */
class BasicProcess {
    String type

    String appGroupID

    FlowStatus status
    String description

    Date createdOn
    String createdBy

    Date lastModifiedOn
    String lastModifiedBy

    Date finishedOn
    String finishedBy
  
    static hasMany = [ nodes: ProcessNode,
                       variables: ProcessVariable,
                       assignees: ProcessAssignee ]

    static constraints = {
        appGroupID(nullable:true)
        description(length:50, nullable:true)
        finishedOn(nullable:true)
        finishedBy(nullable:true)
    }
    
    static mapping = {
        status index: 'IDX_BASIC_PROCESS_1'
        nodes cascade: "all-delete-orphan"
        variables cascade: "all-delete-orphan"
        assignees cascade: "all-delete-orphan"
    }

    def beforeInsert = {
        String applicationID = this.domainClass.grailsApplication
            .mainContext.appExternalID?.toString()
        appGroupID = applicationID
    }
}

grails-app/domain/com/jcatalog/grailsflow/model/process/FlowStatus.groovy
/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.jcatalog.grailsflow.model.process

import org.hibernate.type.YesNoType

/**
 * Status class describes the current condition of entry.
 *
 * The following values of 'statusID' are supported:
 *    statusID = "ACTIVATED" - the entry was activated
 *                             (eg. status for started process
 *                              or status for current process node)
 *    statusID = "SUSPENDED" - the entry was suspended
 *                             (eg. the process node type is 'Wait')
 *    statusID = "KILLED" - the entry was killed
 *                          (eg. the process was killed or deleted by smb. from UI)
 *    statusID = "COMPLETED" - the entry was completed
 *                             (eg. the process was finished successfully)
 *    statusID = "AWAIT_CALLBACK" - the entry was called asynchronous
 *
 * @author Stephan Albers
 * @author July Karpey
 */
class FlowStatus {
    String statusID
    String description
    boolean isFinal = false

    static mapping = {
      statusID index: 'IDX_FLOW_STATUS_1'
      columns {
          isFinal type:YesNoType
      }
    }

    boolean equals(Object o) {
      if (o == null) return false
      if (!(o instanceof FlowStatus)) return false
      return this.statusID.equals(o.statusID)
    }
}

grails-app/domain/com/jcatalog/grailsflow/model/process/ProcessNode.groovy
/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.jcatalog.grailsflow.model.process

import com.jcatalog.grailsflow.model.definition.ProcessNodeDef

/**
 * Process Node represents a node for the process.
 *
 * @author Stephan Albers
 * @author July Antonicheva
 * @author Maria Voitovich
 */
class ProcessNode {
    String branchID = "0"  // 0 for "root" branch
    String nodeID
    String type

    String caller

    FlowStatus status

    Date startedOn
    Date startedExecutionOn
    Date finishedOn
    Date dueOn
    String description

    String event
    ProcessNodeException exception

    String protocolGroup

    static belongsTo = [ process: BasicProcess ]

    static hasMany = [ previousNodes: ProcessNode, nextNodes : ProcessNode ]

    static constraints = {
        caller(nullable:true)
        startedExecutionOn(nullable:true)
        finishedOn(nullable:true)
        dueOn(nullable:true)
        description(nullable:true)
        exception(nullable:true)
        event(nullable:true)
        protocolGroup(nullable:true)
    }

    static mapping = {
      status index: 'IDX_PROCESS_NODE_1'
      nodeID index:'IDX_PROCESS_NODE_3'
      process index:'IDX_PROCESS_NODE_3'
      previousNodes joinTable:[name:'process_node_transition', key:'to_node', column: "from_node"], cascade: "none"
      nextNodes joinTable:[name:'process_node_transition', key:'from_node', column: "to_node"]
    }

    public ProcessNode() {
    }


    public ProcessNode(ProcessNodeDef nodeDef) {
      this.nodeID = nodeDef.nodeID
      this.type = nodeDef.type
      this.protocolGroup = nodeDef.protocolGroup

    }

    static transients = ["assignees" ]

    public Collection<String> getAssignees() {
      return process?.assignees?.findAll() { it.nodeID == this.nodeID }?.collect() { it.assigneeID } ?: []
    }

}

grails-app/controllers/ProcessController.groovy
/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import com.jcatalog.grailsflow.utils.JSONConverter
import com.jcatalog.grailsflow.utils.ConstantUtils
import com.jcatalog.grailsflow.utils.AuthoritiesUtils

import org.apache.commons.lang.StringUtils

import grails.util.GrailsUtil

import com.jcatalog.grailsflow.model.process.BasicProcess
import com.jcatalog.grailsflow.model.process.FlowStatus
import com.jcatalog.grailsflow.model.process.ProcessNode
import com.jcatalog.grailsflow.model.process.ProcessVariable

import com.jcatalog.grailsflow.bean.ProcessDetails
import com.jcatalog.grailsflow.bean.NodeDetails

import com.jcatalog.grailsflow.utils.TranslationUtils

import com.jcatalog.grailsflow.model.graphics.ProcessNodePosition

import org.springframework.web.servlet.support.RequestContextUtils as RCU
import com.jcatalog.grailsflow.status.NodeStatusEnum

import com.jcatalog.grailsflow.process.ProcessSearchParameters
import java.text.ParseException
import grails.converters.JSON
import com.jcatalog.grailsflow.status.ProcessStatusEnum

/**
 * Process controller class is used for displaying process-related views.
 * It is also contains logic for worklist representation.
 *
 * @author Stephan Albers
 * @author July Karpey
 */
class ProcessController extends GrailsFlowSecureController {
    static final String GRAPHIC_NODE_VISITED = "visited"
    static final String GRAPHIC_NODE_ACTIVE = "active"
    static final String GRAPHIC_NODE_UNTOUGHED = "untouched"

    // this is a maximum value for processes size in SQL 'in' clause
    private static final int MAX_PROCESSES_SIZE = 500

    def processManagerService
    def processWorklistService
    def processAdministrationService
    def datePatterns
    // Export service provided by Export plugin
    def exportService
    def additionalWorklistColumns
    def maxResultSize
    def maxRestrictedProcesses
    def isWorklistFilterAvailable

    def index = {
        forward(action: "list", params: params)
    }

    static processNodeJsonProperties = [
            'id', 'branchID', 'caller', 'description', 'dueOn', 'event', 'exception',
            'finishedOn', 'nodeID', 'protocolGroup', 'startedExecutionOn', 'startedOn', 'status', 'type']

  /**
    * ProcessList UI
    */
    def list = {
        flash.message=""
        withFormat {
            html { return [processDetailsList: [],  // show empty list by default
                processClasses: processManagerService.supportedProcessClasses, params: params]}
            json { render([errors: flash.errors, processClasses: processManagerService.supportedProcessClasses] as JSON) }
        }
    }

    /**
     * Shows worklist for current user
     *
     * parameters:
     *   - paging:
     *     -- sort
     *     -- order
     *     -- max
     *     -- offset
     *   - varsFilter.<varName>
     *   - filterVariable
     *   - filterVariableValue
     *   - isEmbedded (TODO: may be remove it)
     *
     */
    def showWorklist = {
        def startOperationTime = System.currentTimeMillis()
        // get paging parameters
        def pagingParameters = getPagingParameters(params)
        if (!pagingParameters.sort ||
            pagingParameters.sort in ["nodeLabel", "processTypeLabel"]) {
            pagingParameters.sort = "startedOn"
        }
        params.max = pagingParameters.max
        String lang = params.lang ? params.lang : RCU.getLocale(request)?.language.toString()

        // get authorities
        def authorities = getUserAuthorities(session)

        // preparing model
        def model = [:]
        def listFilter = [:]
        def worklist
        // prepare filtering if necessary
        if (isWorklistFilterAvailable) {
            // define request variables filter
            def varsFilter = [:]
            params.keySet()?.each() { parameter ->
                if (parameter.startsWith("varsFilter.")
                    && parameter.size() > "varsFilter.".size()) {

                    def procVariable = StringUtils.substringAfter(parameter, "varsFilter.")

                    if (procVariable.endsWith(".list")
                        && parameter.size() > ".list".size()) {
                        // evaluate parameter value to List
                        try {
                            params[parameter] = params[parameter].trim()
                            if (!params[parameter].startsWith("[")) {
                                params[parameter] = "[${params[parameter]}]"
                            }
                            def listValue = new GroovyShell().evaluate(params[parameter])
                            varsFilter[StringUtils.substringBeforeLast(procVariable,".list")] = listValue
                        } catch (Exception e) {
                            log.error("Parameter value cannot be evaluated to List value", e)
                        }
                    } else {
                        varsFilter[procVariable] = params[parameter]
                    }
                }
            }

            listFilter += varsFilter
            if (params.filterVariable && params.filterVariableValue){
                listFilter[params.filterVariable] = params.filterVariableValue
            }

            // get all unfiltered processes
            def availableNodes = processWorklistService
                .getWorklist(authorities, listFilter, pagingParameters.sort, pagingParameters.order, null, null)

            model.varsFilter = varsFilter
            model.filterVariable = params.filterVariable
            model.filterVariableValue = params.filterVariableValue

            // get variables values
            def variableValues = [:]  // map of columnName -> List of available values
            def processVariableValues = [:] // map of columnName -> Map of processID -> process variable
            if (additionalWorklistColumns) {
                def processes = availableNodes.collect(){it.process}.unique()
                if (maxRestrictedProcesses >= processes.size()) {
                          // if we have more then 500 processes in worklist we get variables
                          // by splitting the parameter list into smaller
                          // chunks and then combining the results
                          def pages = Math.round(Math.ceil(processes.size()/MAX_PROCESSES_SIZE))
                          additionalWorklistColumns.each(){ name ->
                              def columnValues = [:]
                              if (availableNodes) {
                                  def variables = []
                                  (0..<pages).each { page->
                                      def useProcesses
                                      if (page*MAX_PROCESSES_SIZE+MAX_PROCESSES_SIZE > processes.size() ) {
                                          useProcesses = processes[page*MAX_PROCESSES_SIZE..-1]
                                      } else {
                                          useProcesses = processes[page*MAX_PROCESSES_SIZE..(page*MAX_PROCESSES_SIZE+MAX_PROCESSES_SIZE-1)]
                                      }
                                      variables.addAll(getVariablesFromProcesses(name, useProcesses))
                                  }
                                  variables.each() { var ->
                                      columnValues.put(var.process.id, var)
                                  }
                                  variableValues.put(name, variables.findAll(){
                                      if (it.value && it.value.trim().size() > 0) {
                                          def item = [:]
                                          item.value = it.value
                                          item.variableValue = it.variableValue
                                          return item
                                      }
                                  }.unique(){
                                      "${it.value}".toString()
                                  }.sort() { "${it.value}".toString() });
                              } else {
                                  variableValues.put(name, []);
                              }
                              processVariableValues.put(name, columnValues)
                          }

                } else {
                    log.info("""There are too many processes '${processes.size()}' for process variables search.
                        Please configure 'maxRestrictedProcesses' value (current value is ${maxRestrictedProcesses}).""")
                    flash.message = g.message(code: 'plugin.grailsflow.message.processes.size.large', args: [processes.size().toString(), maxRestrictedProcesses?.toString()])
                }
            }
            worklist = applyPagingParameters(availableNodes, pagingParameters)
            // get current page items
            model.variableValues = variableValues
            model.processVariableValues = processVariableValues
        } else {
            // get current page items
            worklist = processWorklistService.getWorklist(authorities, listFilter,
                pagingParameters.sort, pagingParameters.order, pagingParameters.max, pagingParameters.offset)

grails-app/views/process/_nodesList.gsp
<!--
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->

<!--
  Template for displaying ProcessVariables on the ProcessDetails UI

  Template parameters:

  required: 
    * nodes              List of nodes objects

 -->

<h3><g:message code="plugin.grailsflow.label.processNodes"/></h3>
<div class="table-responsive">
 <table class="table">
   <thead>
     <tr>
        <th><g:message code="plugin.grailsflow.label.nodeID"/></th>
        <th><g:message code="plugin.grailsflow.label.description"/></th>
        <th><g:message code="plugin.grailsflow.label.status"/></th>
        <th><g:message code="plugin.grailsflow.label.caller"/></th>
        <th><g:message code="plugin.grailsflow.label.startedOn"/></th>
        <th><g:message code="plugin.grailsflow.label.startedExecutionOn"/></th>
        <th><g:message code="plugin.grailsflow.label.finishedOn"/></th>
        <th><g:message code="plugin.grailsflow.label.dueOn"/></th>
      </tr>
   </thead>
   <tbody>
     <g:each in="${nodes}">
          <tr>
             <td><gf:translatedValue translations="${it.label}" default="${it.nodeID}"/></td>
             <td><gf:translatedValue translations="${it.description}" default=""/></td>
             <td>${it.status?.statusID ? g.message(code: 'plugin.grailsflow.label.status.'+it.status?.statusID) : '-'}</td>
             <td>${it.caller}</td>
             <td><gf:displayDateTime value="${it.startedOn}"/></td>
             <td><gf:displayDateTime value="${it.startedExecutionOn}"/></td>
             <td><gf:displayDateTime value="${it.finishedOn}"/></td>
             <td><gf:displayDateTime value="${it.dueOn}"/></td>
          </tr>
     </g:each>
   </tbody>
 </table>
</div>

grails-app/views/process/showWorklist.gsp
<!--
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=10">
    <g:render plugin="grailsflow" template="/commons/global"/>
    <g:if test="${params.isEmbedded == 'true'}">
      <meta name="layout" content="" />
      <r:layoutResources/>
    </g:if>
    <g:else>
      <meta name="layout" content="grailsflow" />
    </g:else>
    <title><g:message code="plugin.grailsflow.title.worklist"/></title>

    <r:script>
      var variableValuesMap = {};
      <g:each var="name" in="${variableValues?.keySet()}">
        variableValuesMap["${name}"] = new Array();
        <g:each var="value" status="i" in="${variableValues[name]}">
          variableValuesMap["${name}"][${i}] = new Option("${value.value}", "${value.variableValue}");
        </g:each>
      </g:each>

      function clearOptions(selectElement) {
        for (var i = selectElement.options.length; i>0;  --i ){
          selectElement.remove(i-1);
        }
      }

      function changeFilterVariable() {
        var name = document.getElementById('filterVariable').value;
        var valueSelect = document.getElementById('filterVariableValue');

        valueSelect.value = "";
        clearOptions(valueSelect);
        if (name == "") {
          var option = new Option("${g.message(code: 'plugin.grailsflow.label.emptyFilterVariable')}", "");
          addOption(valueSelect, option);
          valueSelect.disabled = true;
          return;
        } else {
          if (variableValuesMap[name].length > 0) {
            addOption(valueSelect, new Option("", ""));
            valueSelect.disabled = false;
	        for (var i=0; i < variableValuesMap[name].length; ++i ){
	          var protoOption = variableValuesMap[name][i];
	          var option = new Option(protoOption.text, protoOption.value);
	          addOption(valueSelect, option);
	        }
            return;
          } else {
            addOption(valueSelect, new Option("${g.message(code: 'plugin.grailsflow.label.emptyFilterVariableValue')}", ""));
            valueSelect.disabled = true;
            return;
          }
        }
      }

    </r:script>
  </head>

  <body>
    <h1><g:message code="plugin.grailsflow.title.worklist"/></h1>
    <g:render plugin="grailsflow" template="/commons/messageInfo"/>

    <g:form controller="${params['controller']}" method="POST">
      <g:if test="${params.isEmbedded}">
        <input type="hidden" name="isEmbedded" value="${params.isEmbedded}"/>
      </g:if>
      <g:set var="varsFilterString" value="${['isEmbedded': params.isEmbedded]}"/>

      <g:if test="${isFilterAvailable}">
        <g:each var="parameter" in="${varsFilter?.keySet()}">
          <g:if test="${varsFilter[parameter] instanceof List}">
            <g:hiddenField name="varsFilter.${parameter}.list" value="${varsFilter[parameter].inspect()}"/>
            <g:set var="key" value="${'varsFilter.'+parameter+'.list'}" />
            <g:set var="varsFilterString" value="${varsFilterString + [key : varsFilter[parameter].inspect()]}"/>
          </g:if>
          <g:else>
            <g:hiddenField name="varsFilter.${parameter}" value="${varsFilter[parameter]}"/>
            <g:set var="key" value="${'varsFilter.'+parameter}" />
            <g:set var="varsFilterString" value="${varsFilterString + [key : varsFilter[parameter]]}"/>
          </g:else>
        </g:each>
        <g:set var="varsFilterString" value="${varsFilterString + ['filterVariable' : filterVariable]}"/>
        <g:set var="varsFilterString" value="${varsFilterString + ['filterVariableValue' : filterVariableValue]}"/>

        <g:if test="${additionalColumns}">

          <div class="row">
            <div class="col-md-4">
              <g:message code="plugin.grailsflow.label.filterVariable"/>&nbsp;
              <g:select id="filterVariable" name="filterVariable" value="${filterVariable}" noSelection="['':'']"
                          from="${additionalColumns.keySet()}" onchange = "changeFilterVariable();"
                          optionValue="${{gf.translatedValue(translations: additionalColumns[it], default: it)}}">
              </g:select>
            </div>
            <div class="col-md-3">
              <g:message code="plugin.grailsflow.label.filterVariableValue"/>&nbsp;
              <select id="filterVariableValue" name="filterVariableValue" value="${filterVariableValue}"
                    ${filterVariable && variableValues?.get(filterVariable)?.size() ? '' : 'disabled="true"'}>
                    <g:if test="${! filterVariable}">
                        <option value="" selected="true"><g:message code="plugin.grailsflow.label.emptyFilterVariable"/></option>
                    </g:if>
                    <g:else>
                        <g:if test="${variableValues?.get(filterVariable)?.size()}">
                            <option value="" selected="${! filterVariableValue}"></option>
                            <g:each var="value" in="${variableValues[filterVariable]}">
                                <option value="${value.value}" ${value.value == filterVariableValue ? 'selected="true"' : ''}>
                                    ${value.variableValue}
                                </option>
                            </g:each>
                        </g:if>
                        <g:else>
                            <option value="" selected="true"><g:message code="plugin.grailsflow.label.emptyFilterVariableValue"/></option>
                        </g:else>
                    </g:else>
              </select>
            </div>
            <div class="col-md-5">
              <g:actionSubmit value="${g.message(code: 'plugin.grailsflow.command.filter')}" action="showWorklist" class="btn btn-primary"/>
            </div>
          </div>
        </g:if>
      </g:if>

      <g:if test="${processNodeList}">
      <div class="row margin-top-10">
        <div class="col-md-12">
          <table width="100%" class="table">
            <thead>
              <tr>
                  <gf:sortableColumn property="nodeLabel"
                      defaultOrder="desc" controller="${params['controller']}"
                      title="${g.message(code: 'plugin.grailsflow.label.nodeID')}"
                      action="showWorklist" params="${varsFilterString}"/>
                  <th><g:message code="plugin.grailsflow.label.externalUrl"/></th>
                  <gf:sortableColumn property="processTypeLabel" defaultOrder="desc" controller="${params['controller']}"
                      title="${g.message(code: 'plugin.grailsflow.label.processType')}"
                      action="showWorklist" params="${varsFilterString}"/>
                  <th><g:message code="plugin.grailsflow.label.description"/></th>

                  <g:if test="${additionalColumns}">
                    <g:each var="column" in="${additionalColumns.keySet()}">
                      <gf:sortableColumn property="vars.${column}" defaultOrder="desc" controller="${params['controller']}"
                          title="${gf.translatedValue(translations: additionalColumns[column], default: column)}"
                          action="showWorklist" params="${varsFilterString}"/>
                    </g:each>
                  </g:if>
                  <th><g:message code="plugin.grailsflow.label.caller"/></th>
                  <gf:sortableColumn property="startedOn" title="${g.message(code: 'plugin.grailsflow.label.startedOn')}" defaultOrder="desc"
                      controller="${params['controller']}" action="showWorklist"/>
                  <gf:sortableColumn property="dueOn" title="${g.message(code: 'plugin.grailsflow.label.dueOn')}" defaultOrder="desc"
                      controller="${params['controller']}" action="showWorklist"/>
              </tr>
            </thead>
            <tbody>
              <g:each in="${processNodeList}" var="node">
                <tr>
                  <td>
                    <g:if test="${node.type == com.jcatalog.grailsflow.utils.ConstantUtils.NODE_TYPE_WAIT}">
                      <g:set var="detailsParams" value="${params.isEmbedded ? [isEmbedded: params.isEmbedded] : [:]}"/>
                      <g:link id="${node.id}" controller="${params['controller']}"
                            params="${detailsParams}" action="showNodeDetails">
                        <gf:translatedValue translations="${node.label}" default="${node.nodeID}"/>
                      </g:link>
                    </g:if>
                    <g:else>
                      <gf:translatedValue translations="${node.label}" default="${node.nodeID}"/>
                    </g:else>
                  </td>
                  <td>
                    <gf:generateExternalUrl processNodeId="${node.id}" action="openExternalUrl"
                        controller="process" label="${g.message(code: 'plugin.grailsflow.message.externalUrl')}"/>
                  </td>
                  <td>
                    <gf:translatedValue translations="${node.process.label}" default="${node.process.type}"/>
                  </td>
                  <td><gf:translatedValue translations="${node.description}" default=""/></td>
                    <g:if test="${additionalColumns}">
                      <g:each var="column" in="${additionalColumns.keySet()}">
                        <td>${node.variables[column]?.value?.toString()}</td>
                      </g:each>
                    </g:if>
                  <td>${node.caller}</td>
                  <td><gf:displayDateTime value="${node.startedOn}"/></td>
                  <td><gf:displayDateTime value="${node.dueOn}"/></td>
                </tr>
              </g:each>
            </tbody>
          </table>
          <g:if test="${processNodeList.size() > (grailsApplication.mainContext.maxResultSize)}">
            <div class="paginateButtons">
              <g:paginate total="${itemsTotal}" id="${params.id}" params="${params}"
                controller="${params['controller']}" action="showWorklist"/>
            </div>
          </g:if>
            <br/>
            <r:script>
              function reloadPage() {
                window.location = "${g.createLink(controller: params['controller'], action: params['action'], params: params)}";
              }
            </r:script>

            <div class="buttons">
              <span class="button">
                <input type="button" onclick="reloadPage();" value="${g.message(code: 'plugin.grailsflow.command.refresh')}" class="btn btn-link"/>
              </span>
            </div>
          </div>
      </div>
      </g:if>
      <g:else>
        <div class="bs-callout bs-callout-info"><g:message code="plugin.grailsflow.message.noItems"/></div>
      </g:else>
      </g:form>

      <g:if test="${params.isEmbedded == 'true'}">
        <r:layoutResources/>
      </g:if>
  </body>
</html>